# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page_Cours.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(843, 456)
        self.labelSigle = QtWidgets.QLabel(Dialog)
        self.labelSigle.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSigle.setFont(font)
        self.labelSigle.setObjectName("labelSigle")
        self.labelTitre = QtWidgets.QLabel(Dialog)
        self.labelTitre.setGeometry(QtCore.QRect(10, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTitre.setFont(font)
        self.labelTitre.setObjectName("labelTitre")
        self.labelHeures = QtWidgets.QLabel(Dialog)
        self.labelHeures.setGeometry(QtCore.QRect(10, 250, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHeures.setFont(font)
        self.labelHeures.setObjectName("labelHeures")
        self.textBrowserCours = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserCours.setGeometry(QtCore.QRect(320, 10, 511, 361))
        self.textBrowserCours.setObjectName("textBrowserCours")
        self.labelErreurSigle = QtWidgets.QLabel(Dialog)
        self.labelErreurSigle.setGeometry(QtCore.QRect(10, 100, 271, 16))
        self.labelErreurSigle.setText("")
        self.labelErreurSigle.setObjectName("labelErreurSigle")
        self.labelErreurTitre = QtWidgets.QLabel(Dialog)
        self.labelErreurTitre.setGeometry(QtCore.QRect(10, 220, 271, 16))
        self.labelErreurTitre.setText("")
        self.labelErreurTitre.setObjectName("labelErreurTitre")
        self.labelErreurHeures = QtWidgets.QLabel(Dialog)
        self.labelErreurHeures.setGeometry(QtCore.QRect(10, 340, 271, 16))
        self.labelErreurHeures.setText("")
        self.labelErreurHeures.setObjectName("labelErreurHeures")
        self.lineEditSigle = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigle.setGeometry(QtCore.QRect(10, 50, 271, 41))
        self.lineEditSigle.setObjectName("lineEditSigle")
        self.pushButtonAjouter = QtWidgets.QPushButton(Dialog)
        self.pushButtonAjouter.setGeometry(QtCore.QRect(10, 380, 111, 61))
        self.pushButtonAjouter.setObjectName("pushButtonAjouter")
        self.pushButtonAssocier = QtWidgets.QPushButton(Dialog)
        self.pushButtonAssocier.setGeometry(QtCore.QRect(130, 380, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButtonAssocier.setFont(font)
        self.pushButtonAssocier.setObjectName("pushButtonAssocier")
        self.lineEditTitre = QtWidgets.QLineEdit(Dialog)
        self.lineEditTitre.setGeometry(QtCore.QRect(10, 170, 271, 41))
        self.lineEditTitre.setObjectName("lineEditTitre")
        self.lineEditHeures = QtWidgets.QLineEdit(Dialog)
        self.lineEditHeures.setGeometry(QtCore.QRect(10, 290, 271, 41))
        self.lineEditHeures.setObjectName("lineEditHeures")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSigle.setText(_translate("Dialog", "Sigle du cours"))
        self.labelTitre.setText(_translate("Dialog", "Titre du cours"))
        self.labelHeures.setText(_translate("Dialog", "Nombre d\'heures de cours par semaine"))
        self.pushButtonAjouter.setText(_translate("Dialog", "Ajouter"))
        self.pushButtonAssocier.setText(_translate("Dialog", "Associer un étudiant à un cours"))
