# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page_Association.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(367, 626)
        self.labelEtudiant = QtWidgets.QLabel(Dialog)
        self.labelEtudiant.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelEtudiant.setFont(font)
        self.labelEtudiant.setObjectName("labelEtudiant")
        self.labelCours = QtWidgets.QLabel(Dialog)
        self.labelCours.setGeometry(QtCore.QRect(10, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCours.setFont(font)
        self.labelCours.setObjectName("labelCours")
        self.labelListe = QtWidgets.QLabel(Dialog)
        self.labelListe.setGeometry(QtCore.QRect(10, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelListe.setFont(font)
        self.labelListe.setObjectName("labelListe")
        self.pushButtonAjouter = QtWidgets.QPushButton(Dialog)
        self.pushButtonAjouter.setGeometry(QtCore.QRect(260, 120, 61, 41))
        self.pushButtonAjouter.setObjectName("pushButtonAjouter")
        self.comboBoxEtudiant = QtWidgets.QComboBox(Dialog)
        self.comboBoxEtudiant.setGeometry(QtCore.QRect(10, 40, 231, 41))
        self.comboBoxEtudiant.setObjectName("comboBoxEtudiant")
        self.comboBoxCours = QtWidgets.QComboBox(Dialog)
        self.comboBoxCours.setGeometry(QtCore.QRect(10, 120, 231, 41))
        self.comboBoxCours.setObjectName("comboBoxCours")
        self.listViewCours = QtWidgets.QListView(Dialog)
        self.listViewCours.setGeometry(QtCore.QRect(10, 200, 331, 351))
        self.listViewCours.setObjectName("listViewCours")
        self.pushButtonAssocier = QtWidgets.QPushButton(Dialog)
        self.pushButtonAssocier.setGeometry(QtCore.QRect(120, 560, 111, 41))
        self.pushButtonAssocier.setObjectName("pushButtonAssocier")
        self.labelErreur = QtWidgets.QLabel(Dialog)
        self.labelErreur.setGeometry(QtCore.QRect(246, 10, 101, 16))
        self.labelErreur.setText("")
        self.labelErreur.setObjectName("labelErreur")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelEtudiant.setText(_translate("Dialog", "Étudiants"))
        self.labelCours.setText(_translate("Dialog", "Cours"))
        self.labelListe.setText(_translate("Dialog", "Liste des cours"))
        self.pushButtonAjouter.setText(_translate("Dialog", "+"))
        self.pushButtonAssocier.setText(_translate("Dialog", "Associer"))
